### ISSUE TITLE
support External Search vs 2022

### ISSUE THREAD

**Issue by behroozbc** [Rishabh-V/Visual-Studio-Extensibility-Development#1]
hi 
please add support vs2022 to this useful extension https://marketplace.visualstudio.com/items?itemName=RishabhVerma.searchexternal

**Comment by Rishabh-V** [comment]
Thanks for logging the request. The extension would be updated and available for VS 2022 in couple of weeks time.

**Comment by Rishabh-V** [comment]
[https://marketplace.visualstudio.com/items?itemName=RishabhVerma.ExternalSearch64Bit](https://marketplace.visualstudio.com/items?itemName=RishabhVerma.ExternalSearch64Bit) has 64 bit support and should work in VS 2022. Please try out and let us know if you face any issue. Closing this issue.
